if(THREAD STREQUAL "")
    ERROR("No thread given!")

elseif(${THREAD} STREQUAL "OpenMP")
    find_package(OpenMP)
    if(NOT OPENMP_FOUND)
        ERROR("OpenMP not found!")
    endif()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    add_subdirectory(threads/openmp)
    INFO("Thread Support: OpenMP")

elseif(${THREAD} STREQUAL "Serialized")
    add_subdirectory(threads/serialized)
    INFO("Thread Support: Serialized")

elseif(${THREAD} STREQUAL "None")
    add_subdirectory(threads/none)
    INFO("Thread Support: None")

else()
    INFO("Unknown thread given!")
endif()
